app1:
  build: .
  expose:
    - 80
  command: bash -c "/go/bin/app"

app2:
  build: .
  expose:
    - 80
  command: bash -c "/go/bin/app"

app3:
  build: .
  expose:
    - 80
  command: bash -c "/go/bin/app"

haproxy:
  build: haproxy
  links:
    - app1
    - app2
    - app3
  ports:
    - "80:80"
    - "70:70"

  expose:
    - "80"
    - "70"